name: HelloAction
description: greet someone


inputs:
  who-to-greet: 
    description: who to greet
    required: true
    default: world

runs:
  using: "composite"
  steps:
    - name: Set Greeting
      run: echo "Hello $INPUT_WHO_TO_GREET."
      shell: bash
      env:
        INPUT_WHO_TO_GREET: ${{ inputs.who-to-greet }}

