name: Exercise 5

on:
  push:
    branches:
      - master
      
jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
    - name: Print Hello World
      uses: HelloAction@v2
      with:
          who-to-greet: 'Florence'
