name: Docker CD Pipeline

on:
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code!
        uses: actions/checkout@v4
      - name: login Docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: exercise_3
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/app:latest
      
      # Add more steps here

  # More jobs can be added
