name: Exercise 5

on:
  push:
    branches:
      - master
      
jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
    - name: Print Hello World 
      uses: actions/checkout@v4
    - uses: ./.github/actions/greet_people
      with:
          who-to-greet: 'Florence'
